[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

# Redirect blog to posts
[[redirects]]
  from = "/blog/"
  to = "/posts/"